resource: training/train-new-model
description: "Training-Module"

test:
  main:
    heading:
      args:
        - type: text
        - value: "Training and test"
      button:
        args:
          - type: button
          - value: "Train"
          - style: button
        
      button:
        args:
          - type: button
          - value: "Train and test"
          - style: button
            
      card:
        - name: card__header
          header:
            args:
              - type: text
              - value: "Training and Testing Data"

        - name: card__body
          switch:
            label: "Repeat training"
            args:
              - type: button
              - style: switch
              - adjacentTo: label             

      card:
        - name: card__header
          header:
            args:
              - type: text
              - value: "Planned training"

        - name: card__body
          input:
            label: "Starting from"
            args:
              - type: input
              - style: timepicker

          select: 
            span: "Days"
            args:
              - type: checkbox
              options:
                options:
                - name: "Monday"
                - name: "Tuesday"
                - name: "Wednesday"
                - name: "Thursday"
                - name: "Friday"
                - name: "Saturday"
                - name: "Sunday"


          input:
            label: "Training time"  
            args:
              - type: input
              - style: timepicker   

      bottom_section:
        button:
          args:
            - type: button
            - value: "Save"
            - style: button
